pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-maorsh6-credentials') // הרשאות Docker Hub שלך
        DEPLOY_SERVER = '192.168.68.100'
    }
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/maorsh1/project-14.12.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t maorsh6/my-web-app:latest .'
            }
        }
        stage('Push Docker Image') {
            steps {
                sh '''
                echo $DOCKERHUB_CREDENTIALS | docker login -u maorsh6 --password-stdin
                docker push maorsh6/my-web-app:latest
                '''
            }
        }
        stage('Deploy to Server') {
            steps {
                sh '''
                ssh $DEPLOY_SERVER "
                    docker pull maorsh6/my-web-app:latest &&
                    docker stop web-app || true &&
                    docker rm web-app || true &&
                    docker run -d --name web-app -p 80:8080 maorsh6/my-web-app:latest
                "
                '''
            }
        }
    }
}
